#include "../TYPES.H"
#include "MEM_MAP.H"
#include "MFP.H"

IO_PORT8 MFP_IERA = (IO_PORT8) MFP_IERA_ADDR;
IO_PORT8 MFP_IERB = (IO_PORT8) MFP_IERB_ADDR;
IO_PORT8 MFP_ISRA = (IO_PORT8) MFP_ISRA_ADDR;
IO_PORT8 MFP_ISRB = (IO_PORT8) MFP_ISRB_ADDR;
IO_PORT8 MFP_IMRA = (IO_PORT8) MFP_IMRA_ADDR;
IO_PORT8 MFP_IMRB = (IO_PORT8) MFP_IMRB_ADDR;
IO_PORT8 MFP_VR   = (IO_PORT8) MFP_VR_ADDR;
IO_PORT8 MFP_TACR = (IO_PORT8) MFP_TACR_ADDR;
IO_PORT8 MFP_TADR = (IO_PORT8) MFP_TADR_ADDR;

